FROM ubuntu:20.04
# This is a comment
LABEL maintainer="Treenut Yusufee" email="zignut1035@gmail.com"
RUN echo "hello world" >> helloworld.txt
RUN cat helloworld.txt
#run is for build, CMD is when we start an container from image